# Generated by Django 3.2.7 on 2021-09-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cMail',
            new_name='cEmail',
        ),
    ]
